language: cpp
dist: trusty
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - g++-5
jobs:
  include:
    - stage: build
      script:
        - export CC=gcc-5
        - export CXX=g++-5
        - mkdir build
        - cd build
        - cmake ../
        - make pufferfish

branches:
  only:
    - ext_compress
